site_name: Moje projekty
site_author: Eliasz Nowicki
site_url: https://goldmanski.github.io/ds_ai_portfolio
site_description: >-
    Projekty z obszaru Data Science i AI

repo_name: Goldmanski/ds_ai_portfolio
repo_url: https://github.com/Goldmanski/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: yellow

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Titanic": titanic/index.md
- Poprzednie projekty:
  - "Iris": iris/index.md

